"""
Mostashar Voice — Production REST API (ElevenLabs-style)

Clean, stable HTTP/WebSocket API consumable from any client (NestJS, OpenAI SDK
patterns, curl, browser fetch, etc.).

API conventions (mirror ElevenLabs where reasonable):
  - All endpoints under /v1/
  - Auth: header `xi-api-key: <key>` OR `Authorization: Bearer <key>` (set MV_API_KEY env to enable)
  - Voice CRUD:
      GET    /v1/voices                       → list
      GET    /v1/voices/{voice_id}            → detail
      GET    /v1/voices/{voice_id}/preview    → reference audio (WAV)
      POST   /v1/voices/add                   → multipart clone
      DELETE /v1/voices/{voice_id}
  - TTS:
      POST   /v1/text-to-speech/{voice_id}           → full WAV
      POST   /v1/text-to-speech/{voice_id}/stream    → chunked PCM (HTTP)
      WS     /v1/text-to-speech/{voice_id}/ws        → WebSocket (more control)
  - Models:
      GET    /v1/models
  - STT / Transcription:
      POST   /v1/speech-to-text         → multipart audio → {"text": "...", "language": "ar"}
      POST   /v1/transcribe             → multipart audio → {segments, diarization, timestamps}
  - Live Conversation (S2S):
      WS     /v1/conversation/ws        → bidirectional speech-to-speech voice agent
  - Health:
      GET    /v1/health
  - Docs:
      GET    /docs       (Swagger UI auto-generated by FastAPI)
      GET    /openapi.json

Errors:
  Standard JSON shape: {"error": {"code": "...", "message": "...", "status": int}}

Audio output formats supported on output_format query/body param:
  - pcm_24000  → raw PCM int16 LE 24kHz mono (chunked)
  - wav        → WAV with header (full or chunked-with-fixed-header)

Run:
  env MV_MODEL=aoi-ot/VibeVoice-Large MV_DIFF_STEPS=15 MV_API_KEY=secret123 python server_v5_api.py
"""
from __future__ import annotations

import os
import io
import time
import json
import asyncio
import threading
import struct
import uuid
import re
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional, AsyncGenerator

import numpy as np
import soundfile as sf
import librosa
import torch
import transformers as _hf
_hf.logging.set_verbosity_error()

# transformers logger crashes when any config holds a torch.dtype value because
# it tries to JSON-dump it on logger.info(f"{config}"). Patch json.dumps to
# stringify torch.dtype rather than raise.
_orig_json_dumps = json.dumps
def _safe_json_dumps(obj, **kw):
    def _default(o):
        if isinstance(o, torch.dtype):
            return str(o).replace("torch.", "")
        raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
    if "default" not in kw:
        kw["default"] = _default
    return _orig_json_dumps(obj, **kw)
json.dumps = _safe_json_dumps
from fastapi import (
    FastAPI, WebSocket, WebSocketDisconnect, UploadFile, File, Form,
    HTTPException, Header, Depends, Query, Path as PathParam,
)
from fastapi.responses import StreamingResponse, FileResponse, Response, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# --- config ---
MODEL_NAME = os.environ.get("MV_MODEL", "aoi-ot/VibeVoice-Large")
ASR_MODEL_NAME = os.environ.get("MV_ASR_MODEL", "microsoft/VibeVoice-ASR")
ASR_ENABLED = os.environ.get("MV_ASR_ENABLED", "1") not in ("0", "false", "False", "")
LLM_MODEL_NAME = os.environ.get("MV_LLM_MODEL", "Qwen/Qwen2.5-7B-Instruct")
LLM_ENABLED = os.environ.get("MV_LLM_ENABLED", "1") not in ("0", "false", "False", "")
# Gemma 4 sidecar — direct audio→text chat, runs in its own venv on the
# same host. When reachable, /v1/conversation/ws prefers it over the
# VibeVoice-ASR + Qwen pipeline (faster, ~half the VRAM, native audio
# understanding so no transcript drift). Set MV_GEMMA4_URL="" to force
# the fallback path.
GEMMA4_URL = os.environ.get("MV_GEMMA4_URL", "http://127.0.0.1:8082")
DIFFUSION_STEPS = int(os.environ.get("MV_DIFF_STEPS", "15"))
CFG_SCALE = float(os.environ.get("MV_CFG", "1.8"))
SAMPLE_RATE = 24000
ASR_SAMPLE_RATE = 24000  # ASR also expects 24kHz
INPUT_SAMPLE_RATE = 16000  # mic capture from clients (resampled before ASR)
DEFAULT_REF = os.environ.get("MV_REF", "/workspace/refs/01.mp3")
VOICES_DIR = os.environ.get("MV_VOICES_DIR", "/workspace/refs/voices")
API_KEY = os.environ.get("MV_API_KEY", "")  # if empty, auth is disabled
os.makedirs(VOICES_DIR, exist_ok=True)

SESSION_LOG_DIR = os.environ.get(
    "MV_SESSION_LOG_DIR", "/workspace/conversation_logs"
)
os.makedirs(SESSION_LOG_DIR, exist_ok=True)


class SessionLog:
    """Per-WebSocket recorder. Saves each turn's audio + transcript +
    response to disk so the user can recover from a dropped connection.

    Layout:
      {SESSION_LOG_DIR}/{session_id}/
          turn_{N}.wav        ← raw 16kHz user audio
          transcript.jsonl    ← one JSON line per turn
    """

    def __init__(self, session_id: str) -> None:
        self.session_id = session_id
        self.dir = os.path.join(SESSION_LOG_DIR, session_id)
        os.makedirs(self.dir, exist_ok=True)
        self._idx = 0
        self._log_path = os.path.join(self.dir, "transcript.jsonl")

    def next_turn_idx(self) -> int:
        self._idx += 1
        return self._idx

    def save_audio(self, idx: int, audio: np.ndarray, sr: int) -> str:
        path = os.path.join(self.dir, f"turn_{idx:03d}.wav")
        sf.write(path, audio, sr)
        return path

    def record_turn(
        self, idx: int, audio_path: str, transcript: str, response: str
    ) -> None:
        try:
            with open(self._log_path, "a", encoding="utf-8") as f:
                f.write(json.dumps({
                    "turn": idx,
                    "ts": int(time.time()),
                    "audio": os.path.basename(audio_path),
                    "transcript": transcript,
                    "response": response,
                }, ensure_ascii=False) + "\n")
        except Exception as e:
            print(f"[session-log] failed to record turn {idx}: {e}")


DEFAULT_SYSTEM_PROMPT = (
    "أنت مساعد صوتي ذكي لمنصة مستشار. مهمتك أن تجيب على المستخدم بنبرة "
    "ودودة ومحترفة.\n\n"
    "قواعد صارمة يجب الالتزام بها دائماً:\n"
    "1. ردّ دائماً بالعربية الفصحى الواضحة. ممنوع منعاً تاماً استخدام الصينية "
    "أو الإنجليزية أو أي لغة غير العربية، حتى لو كان كلام المستخدم غامضاً "
    "أو مقطوعاً أو فيه أخطاء.\n"
    "2. اجعل ردك قصيراً جداً: جملة واحدة أو جملتان فقط. الردّ سيُحوَّل إلى "
    "صوت ويسمعه المستخدم مباشرة، فالطول يُتعب الأذن.\n"
    "3. اكتب نصاً طبيعياً منطوقاً — لا قوائم، لا Markdown، لا أرقام بنود، "
    "لا رموز خاصة، لا روابط.\n"
    "4. أضف التشكيل الكامل (الفتحة، الضمة، الكسرة، السكون، الشدّة، التنوين) "
    "على الكلمات المهمة لتحسين النطق.\n"
    "5. إذا كلام المستخدم غير واضح أو مقطوع، اطلب منه أن يعيد بإيجاز "
    "بدلاً من التخمين."
)


# Structural markers VibeVoice-ASR emits inside transcripts. We strip
# them before:
#   - sending the transcript to the LLM (otherwise it treats them as
#     part of the user's intent and replies in Chinese on the long ones)
#   - showing the transcript in the UI (the user just wants to see what
#     was said, not the model's internal annotations)
_ASR_NOISE_TOKENS_RE = re.compile(
    r"\[\s*(?:silence|noise|music|unintelligible(?:\s+speech)?|"
    r"applause|laughter|background\s+(?:noise|music)|crosstalk|inaudible)"
    r"\s*\]",
    re.IGNORECASE,
)


def _clean_asr_text_for_display(text: str) -> str:
    """Remove ASR-only markers but keep all transcribed words. Suitable
    for both the UI transcript bubble and the LLM input."""
    cleaned = _ASR_NOISE_TOKENS_RE.sub(" ", text)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned


# Backwards-compat alias for the LLM-cleanup call sites.
def _clean_asr_text_for_llm(text: str) -> str:
    return _clean_asr_text_for_display(text)


# VibeVoice-ASR's streaming code path requires extra kwargs that our
# patched community fork doesn't accept (raises
# "VibeVoiceAcousticTokenizerModel.encode() got an unexpected keyword
# argument"). The streaming threshold is 60 s, so we cap conversation
# audio just below that to stay on the safe non-streaming path.
ASR_MAX_AUDIO_SAMPLES = int(55 * ASR_SAMPLE_RATE)


# Detect script of LLM output. If the response is dominated by non-Arabic
# scripts, we know the LM hallucinated and we retry with a stricter prompt.
_ARABIC_RE = re.compile(r"[؀-ۿݐ-ݿࢠ-ࣿﭐ-﷿ﹰ-﻿]")
_CJK_RE = re.compile(r"[぀-ヿ一-鿿가-힯]")


def _looks_arabic(text: str, min_ratio: float = 0.4) -> bool:
    """Returns False if the response is dominated by CJK (Chinese hallucination)
    or has almost no Arabic characters."""
    if not text or not text.strip():
        return True  # empty — let it through, caller will handle
    letters = [c for c in text if c.isalpha()]
    if not letters:
        return True
    arabic = sum(1 for c in letters if _ARABIC_RE.match(c))
    cjk = sum(1 for c in letters if _CJK_RE.match(c))
    if cjk > arabic:
        return False
    return (arabic / len(letters)) >= min_ratio

# --- shared state ---
processor = None
model = None
asr_processor = None
asr_model = None
llm_model = None
llm_tokenizer = None
voice_profiles: dict[str, dict] = {}

# --- concurrency: serialize within each model (different models can run in parallel) ---
# Single GPU can only run one diffusion/LM forward pass per model at a time
# without contention. Locks here turn arrival of N concurrent requests into a
# clean FIFO queue rather than crashing the GPU. Different models still run
# in parallel: User A's TTS can stream while User B's ASR transcribes.
_tts_lock: Optional["asyncio.Lock"] = None
_asr_lock: Optional["asyncio.Lock"] = None
_llm_lock: Optional["asyncio.Lock"] = None


class _ModelStats:
    """Per-model FIFO queue depth + cumulative wait/run timing."""
    __slots__ = ("queued", "running", "served", "total_wait_ms", "total_run_ms")

    def __init__(self) -> None:
        self.queued = 0
        self.running = 0
        self.served = 0
        self.total_wait_ms = 0.0
        self.total_run_ms = 0.0

    def snapshot(self) -> dict:
        avg_wait = self.total_wait_ms / self.served if self.served else 0.0
        avg_run = self.total_run_ms / self.served if self.served else 0.0
        return {
            "queued": self.queued,
            "running": self.running,
            "served": self.served,
            "avg_wait_ms": round(avg_wait, 1),
            "avg_run_ms": round(avg_run, 1),
        }


_tts_stats = _ModelStats()
_asr_stats = _ModelStats()
_llm_stats = _ModelStats()


@asynccontextmanager
async def _serialize(lock: "asyncio.Lock", stats: _ModelStats):
    """Wait our turn on a model, then run. Tracks queue depth + wait timing."""
    stats.queued += 1
    t_enq = time.time()
    try:
        async with lock:
            wait_ms = (time.time() - t_enq) * 1000
            stats.queued -= 1
            stats.running += 1
            t_run = time.time()
            try:
                yield
            finally:
                stats.running -= 1
                stats.served += 1
                stats.total_wait_ms += wait_ms
                stats.total_run_ms += (time.time() - t_run) * 1000
    except BaseException:
        # If the caller was cancelled while waiting, still release the queue slot.
        if stats.queued > 0:
            stats.queued -= 1
        raise


# ============================================================
# Models (Pydantic)
# ============================================================
class VoiceSettings(BaseModel):
    cfg_scale: float = Field(default=1.8, ge=1.0, le=3.0)
    diffusion_steps: int = Field(default=15, ge=5, le=60)
    seed: int = Field(default=42)


class TTSRequest(BaseModel):
    # Up to 200,000 chars ≈ 90 min of speech — VibeVoice-Large handles
    # long-form single-pass without "stitching" between paragraphs.
    text: str = Field(..., min_length=1, max_length=200_000)
    model_id: str = Field(default="vibevoice-large")
    output_format: str = Field(default="pcm_24000", pattern="^(pcm_24000|wav)$")
    voice_settings: Optional[VoiceSettings] = None
    # When true, run the input text through Qwen first to add Arabic
    # diacritics (تشكيل) and light punctuation. Improves pronunciation
    # noticeably on bare text but adds ~300-1500 ms before TTS starts.
    auto_diacritize: bool = Field(default=False)


class VoiceMeta(BaseModel):
    voice_id: str
    name: str
    language: str
    dur_s: float
    preview_url: str
    created_at: Optional[int]


class VoicesListResponse(BaseModel):
    voices: list[VoiceMeta]


class CloneResponse(BaseModel):
    voice_id: str
    name: str
    language: str
    dur_s: float


class ModelInfo(BaseModel):
    model_id: str
    name: str
    languages: list[str]
    can_clone: bool
    description: str


class HealthResponse(BaseModel):
    status: str
    model: str
    diffusion_steps: int
    voices_count: int
    gpu_mem_gb: float
    version: str
    asr_loaded: bool = False
    asr_model: Optional[str] = None
    llm_loaded: bool = False
    llm_model: Optional[str] = None


class TranscriptSegment(BaseModel):
    start_time: float
    end_time: float
    speaker_id: int
    text: str


class STTResponse(BaseModel):
    text: str
    language: str = "ar"
    duration_s: float


class TranscribeResponse(BaseModel):
    text: str
    language: str = "ar"
    duration_s: float
    speakers_count: int
    segments: list[TranscriptSegment]
    generation_ms: float


class DialogueLine(BaseModel):
    speaker: int = Field(..., ge=1, le=4, description="1-indexed speaker number")
    text: str = Field(..., min_length=1, max_length=5000)


class DialogueRequest(BaseModel):
    speakers: list[str] = Field(
        ..., min_length=1, max_length=4,
        description="Voice IDs in speaker order. Speaker 1 = speakers[0], etc.",
    )
    lines: list[DialogueLine] = Field(..., min_length=1, max_length=200)
    voice_settings: Optional[VoiceSettings] = None
    output_format: str = Field(default="wav", pattern="^(pcm_24000|wav)$")


# ============================================================
# Auth
# ============================================================
def require_api_key(
    xi_api_key: Optional[str] = Header(None, alias="xi-api-key"),
    authorization: Optional[str] = Header(None),
):
    """Validate API key. If MV_API_KEY env is unset, auth is bypassed."""
    if not API_KEY:
        return
    candidate = xi_api_key
    if not candidate and authorization and authorization.lower().startswith("bearer "):
        candidate = authorization[7:]
    if candidate != API_KEY:
        raise HTTPException(status_code=401, detail="invalid_api_key")


# ============================================================
# Voice persistence
# ============================================================
def _meta_path(voice_id: str) -> str: return os.path.join(VOICES_DIR, f"{voice_id}.json")
def _wav_path(voice_id: str) -> str: return os.path.join(VOICES_DIR, f"{voice_id}.wav")


def _slugify(s: str) -> str:
    # keep ASCII alnum + Arabic block + hyphen/underscore
    s = re.sub(r"[^\w؀-ۿ\-]+", "-", (s or "").strip(), flags=re.UNICODE)
    s = re.sub(r"-+", "-", s).strip("-")
    return s[:40] or "voice"


def _load_voice_from_disk(voice_id: str) -> Optional[dict]:
    wp = _wav_path(voice_id)
    if not os.path.exists(wp):
        return None
    audio_np, _ = librosa.load(wp, sr=SAMPLE_RATE)
    meta = {"voice_id": voice_id, "name": voice_id, "language": "ar"}
    mp = _meta_path(voice_id)
    if os.path.exists(mp):
        try: meta.update(json.load(open(mp, encoding="utf-8")))
        except Exception: pass
    profile = {
        "voice_id": voice_id,
        "ref_audio_np": audio_np,
        "ref_audio_dur_s": len(audio_np) / SAMPLE_RATE,
        "name": meta.get("name", voice_id),
        "language": meta.get("language", "ar"),
        "created_at": meta.get("created_at"),
    }
    voice_profiles[voice_id] = profile
    return profile


def _get_voice(voice_id: str) -> dict:
    if voice_id in voice_profiles:
        return voice_profiles[voice_id]
    p = _load_voice_from_disk(voice_id)
    if p is not None:
        return p
    raise HTTPException(status_code=404, detail={"error": {"code": "voice_not_found", "message": f"voice {voice_id} not found", "status": 404}})


def _save_voice(voice_id: str, audio_np: np.ndarray, name: str, language: str) -> dict:
    if len(audio_np) > 30 * SAMPLE_RATE:
        audio_np = audio_np[: 30 * SAMPLE_RATE]
    # NOTE: we deliberately do NOT denoise references at upload time —
    # earlier experiments with noisereduce on edge-tts MP3 sources
    # *amplified* HF artifacts. Speech-band content is preserved best by
    # leaving the reference untouched and applying a surgical low-pass on
    # the model's *output* instead (see _lowpass_clean / _StreamingLowpass).
    sf.write(_wav_path(voice_id), audio_np, SAMPLE_RATE)
    meta = {
        "voice_id": voice_id,
        "name": name,
        "language": language,
        "created_at": int(time.time()),
        "dur_s": len(audio_np) / SAMPLE_RATE,
    }
    with open(_meta_path(voice_id), "w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)
    profile = {
        "voice_id": voice_id,
        "ref_audio_np": audio_np,
        "ref_audio_dur_s": meta["dur_s"],
        "name": name,
        "language": language,
        "created_at": meta["created_at"],
    }
    voice_profiles[voice_id] = profile
    return profile


# ============================================================
# Audio helpers
# ============================================================
def _wav_header(num_samples: int, sr: int = SAMPLE_RATE, channels: int = 1, bits: int = 16) -> bytes:
    """Standard WAV header for raw PCM16."""
    byte_rate = sr * channels * bits // 8
    block_align = channels * bits // 8
    data_size = num_samples * block_align
    return (
        b"RIFF" + struct.pack("<I", 36 + data_size) + b"WAVE"
        + b"fmt " + struct.pack("<IHHIIHH", 16, 1, channels, sr, byte_rate, block_align, bits)
        + b"data" + struct.pack("<I", data_size)
    )


def _wav_streaming_header(sr: int = SAMPLE_RATE) -> bytes:
    """WAV header with unknown length (data_size = 0xFFFFFFFF) for streaming."""
    return _wav_header(0xFFFFFFFF // 2, sr)


def _chunk_to_pcm_bytes(audio_tensor: torch.Tensor) -> bytes:
    a = audio_tensor.detach().cpu().float().numpy().flatten()
    a = (np.clip(a, -1.0, 1.0) * 32767).astype(np.int16)
    return a.tobytes()


# ============================================================
# Generation (shared between non-streaming + streaming)
# ============================================================
def _format_speaker_text(text: str, speaker: int = 1) -> str:
    """Format text so VibeVoice reads it as one natural-flowing utterance.

    VibeVoice interprets every `Speaker N:` line break as a turn boundary
    and inserts a noticeable pause between turns. That's right for a
    dialogue but wrong for an article.

    Strategy:
      - Single newlines inside a paragraph → treated as soft wraps;
        joined with a space so the speaker reads continuously and the
        cadence is driven by punctuation only.
      - Double newlines (\\n\\n) → real paragraph breaks; kept as
        separate `Speaker N:` turns so the listener gets a natural pause.

    This gives the model what it expects (turn-tagged input) without the
    awkward "speak-pause-speak" the previous one-prefix-per-line approach
    produced on multi-line articles.
    """
    paragraphs = [p for p in text.replace("\r\n", "\n").split("\n\n")]
    cleaned_paras: list[str] = []
    for para in paragraphs:
        # Collapse soft wraps inside a paragraph: "line1\nline2" → "line1 line2"
        joined = " ".join(ln.strip() for ln in para.split("\n") if ln.strip())
        if joined:
            cleaned_paras.append(joined)
    if not cleaned_paras:
        return f"Speaker {speaker}: "
    return "\n".join(f"Speaker {speaker}: {p}" for p in cleaned_paras)


def _lowpass_clean(audio: np.ndarray, sr: int = SAMPLE_RATE, cutoff_hz: int = 10000) -> np.ndarray:
    """Deterministic low-pass filter — removes the highest-band hiss /
    hallucinated 'music' / MP3-derived ringing without touching the
    sibilant range.

    Cutoff is at 10 kHz: human speech content is mostly <4 kHz, sibilants
    (س, ش, ف, ث, خ, ح) carry energy up to ~8-10 kHz, and the MP3-derived
    artifacts the user hears as 'music/wind' sit above 10-12 kHz. Cutting
    at 10 kHz keeps the bite of the consonants and the natural air of the
    voice while silencing the artifact band.

    Earlier we tried 7.5 kHz which was too aggressive — output sounded
    slightly muffled because /s/ /sh/ partially attenuated. Earlier still
    we tried `noisereduce` (spectral gating) and it *amplified* HF noise
    (ratio went 0.05 → 0.17). A 10 kHz Butterworth is the sweet spot.
    """
    try:
        from scipy import signal as sps
    except Exception:
        return audio
    if len(audio) < 64:
        return audio
    try:
        sos = sps.butter(N=8, Wn=cutoff_hz, btype="low", fs=sr, output="sos")
        cleaned = sps.sosfiltfilt(sos, audio.astype(np.float32, copy=False))
        return cleaned.astype(np.float32, copy=False)
    except Exception as e:
        print(f"[lowpass] failed, returning original: {e}")
        return audio


class _StreamingLowpass:
    """Stateful low-pass for streaming chunks — preserves filter continuity
    across boundaries so we don't introduce clicks every chunk."""

    def __init__(self, cutoff_hz: int = 10000, sr: int = SAMPLE_RATE, order: int = 6) -> None:
        from scipy import signal as sps
        self._sos = sps.butter(N=order, Wn=cutoff_hz, btype="low", fs=sr, output="sos")
        # Per-section initial conditions, primed to a quiet start.
        self._zi = sps.sosfilt_zi(self._sos) * 0.0

    def __call__(self, chunk: np.ndarray) -> np.ndarray:
        if len(chunk) < 8:
            return chunk
        from scipy import signal as sps
        out, self._zi = sps.sosfilt(self._sos, chunk.astype(np.float32, copy=False), zi=self._zi)
        return out.astype(np.float32, copy=False)


def _trim_audio_tail(
    audio: np.ndarray,
    sr: int = SAMPLE_RATE,
    top_db: int = 35,
    pad_s: float = 0.15,
    min_keep_s: float = 0.5,
) -> np.ndarray:
    """Trim trailing silence/noise that VibeVoice sometimes appends.

    The diffusion head occasionally emits low-energy hiss or stray sound
    after the actual content ends. We find the last "voiced" interval
    above `top_db` below peak and cut just past it (with a small pad so
    the natural decay isn't clipped).
    """
    if len(audio) < int(sr * min_keep_s):
        return audio
    try:
        intervals = librosa.effects.split(
            audio, top_db=top_db, frame_length=2048, hop_length=512
        )
        if len(intervals) == 0:
            return audio
        last_end = int(intervals[-1][1])
        end = min(len(audio), last_end + int(pad_s * sr))
        # Sanity: never trim more than half the clip.
        if end < int(0.5 * len(audio)):
            return audio
        return audio[:end]
    except Exception:
        return audio


def _generate_full(text: str, voice_id: str, settings: Optional[VoiceSettings] = None) -> np.ndarray:
    """Synchronous full generation, returns float32 audio (tail-trimmed)."""
    profile = _get_voice(voice_id)
    if settings:
        model.set_ddpm_inference_steps(num_steps=settings.diffusion_steps)
    speaker_text = _format_speaker_text(text)
    inputs = processor(
        text=[speaker_text],
        voice_samples=[[profile["ref_audio_np"]]],
        return_tensors="pt", padding=True,
    )
    inputs = {k: (v.to("cuda") if hasattr(v, "to") else v) for k, v in inputs.items()}
    torch.manual_seed(settings.seed if settings else 42)
    with torch.no_grad():
        out = model.generate(
            **inputs, max_new_tokens=None,
            cfg_scale=settings.cfg_scale if settings else CFG_SCALE,
            tokenizer=processor.tokenizer,
            generation_config={"do_sample": False, "num_beams": 1},
            verbose=False, show_progress_bar=False,
        )
    audio = out.speech_outputs[0].cpu().float().numpy().flatten()
    audio = _lowpass_clean(audio)
    return _trim_audio_tail(audio)


def _generate_dialogue(
    lines: list[DialogueLine],
    speaker_voice_ids: list[str],
    settings: Optional[VoiceSettings] = None,
) -> np.ndarray:
    """Generate a multi-speaker dialogue in a single VibeVoice forward pass.

    Each speaker has its own reference audio; VibeVoice automatically
    switches voices on `Speaker N:` line breaks. We build the full script
    once and let the model handle prosody continuity across turns.
    """
    profiles = [_get_voice(vid) for vid in speaker_voice_ids]
    speaker_refs = [p["ref_audio_np"] for p in profiles]

    if settings:
        model.set_ddpm_inference_steps(num_steps=settings.diffusion_steps)

    # Validate every line refers to a defined speaker.
    for line in lines:
        if line.speaker < 1 or line.speaker > len(speaker_voice_ids):
            raise HTTPException(
                400,
                f"line refers to speaker {line.speaker} but only "
                f"{len(speaker_voice_ids)} voices were provided",
            )

    script = "\n".join(f"Speaker {line.speaker}: {line.text.strip()}" for line in lines)
    inputs = processor(
        text=[script],
        voice_samples=[speaker_refs],
        return_tensors="pt",
        padding=True,
    )
    inputs = {k: (v.to("cuda") if hasattr(v, "to") else v) for k, v in inputs.items()}
    torch.manual_seed(settings.seed if settings else 42)
    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=None,
            cfg_scale=settings.cfg_scale if settings else CFG_SCALE,
            tokenizer=processor.tokenizer,
            generation_config={"do_sample": False, "num_beams": 1},
            verbose=False,
            show_progress_bar=False,
        )
    audio = out.speech_outputs[0].cpu().float().numpy().flatten()
    audio = _lowpass_clean(audio)
    return _trim_audio_tail(audio)


def _np_to_pcm_bytes(audio_np: np.ndarray) -> bytes:
    """Float32 → PCM16LE bytes. Mirrors `_chunk_to_pcm_bytes` for numpy arrays."""
    a = (np.clip(audio_np, -1.0, 1.0) * 32767).astype(np.int16)
    return a.tobytes()


# Trailing-chunk buffer for tail-noise trimming. The lower the number, the
# faster TTFA — but we need enough lookback to detect "diffusion head got
# bored and started emitting hiss" at the end. 1 chunk strikes the right
# balance: TTFA cost is at most ~80 ms (one chunk), and we still have one
# chunk of look-ahead to filter the tail. Increase only if tail noise leaks
# back through.
_TAIL_BUFFER_CHUNKS = 1


async def _generate_stream(text: str, voice_id: str, settings: Optional[VoiceSettings] = None) -> AsyncGenerator[bytes, None]:
    """Async generator yielding PCM16LE chunks as the model produces them.

    Buffers the last few chunks so we can trim noise/hiss the model
    sometimes emits after the actual content. Adds <1 s to perceived
    end-of-utterance latency but eliminates the "wind/music" tail.
    """
    from vibevoice.modular.streamer import AudioStreamer

    profile = _get_voice(voice_id)
    if settings:
        model.set_ddpm_inference_steps(num_steps=settings.diffusion_steps)
    speaker_text = _format_speaker_text(text)
    inputs = processor(
        text=[speaker_text],
        voice_samples=[[profile["ref_audio_np"]]],
        return_tensors="pt", padding=True,
    )
    inputs = {k: (v.to("cuda") if hasattr(v, "to") else v) for k, v in inputs.items()}

    streamer = AudioStreamer(batch_size=1, stop_signal=None, timeout=30.0)
    cfg = settings.cfg_scale if settings else CFG_SCALE
    seed = settings.seed if settings else 42

    def run_generate():
        try:
            torch.manual_seed(seed)
            with torch.no_grad():
                model.generate(
                    **inputs, max_new_tokens=None, cfg_scale=cfg,
                    tokenizer=processor.tokenizer,
                    generation_config={"do_sample": False, "num_beams": 1},
                    verbose=False, show_progress_bar=False,
                    audio_streamer=streamer,
                )
        except Exception:
            import traceback; traceback.print_exc()
            streamer.end()

    threading.Thread(target=run_generate, daemon=True).start()
    loop = asyncio.get_event_loop()
    tail_buffer: list[torch.Tensor] = []
    # Stateful low-pass keeps filter continuity across chunk boundaries —
    # no clicks at boundaries, removes HF hiss / hallucinated 'music'.
    lp = _StreamingLowpass()

    def _chunk_to_filtered_pcm(t: torch.Tensor) -> bytes:
        f32 = t.detach().cpu().float().numpy().flatten()
        f32 = lp(f32)
        a16 = (np.clip(f32, -1.0, 1.0) * 32767).astype(np.int16)
        return a16.tobytes()

    while True:
        try:
            chunk = await loop.run_in_executor(None, lambda: streamer.audio_queues[0].get(timeout=30.0))
        except Exception:
            break
        if chunk is None or chunk is streamer.stop_signal:
            # End of stream — run tail-trim across the buffered chunks.
            if tail_buffer:
                tail_np = np.concatenate([
                    t.detach().cpu().float().numpy().flatten() for t in tail_buffer
                ])
                tail_np = lp(tail_np)
                trimmed = _trim_audio_tail(tail_np)
                if len(trimmed) > 0:
                    yield _np_to_pcm_bytes(trimmed)
            break
        tail_buffer.append(chunk)
        if len(tail_buffer) > _TAIL_BUFFER_CHUNKS:
            yield _chunk_to_filtered_pcm(tail_buffer.pop(0))


# ============================================================
# ASR (Speech-to-Text) — VibeVoice-ASR
# ============================================================
def _decode_audio_bytes(audio_bytes: bytes, sr: int = ASR_SAMPLE_RATE) -> np.ndarray:
    """Decode mp3/wav/m4a/webm/ogg/opus → mono float32 at sr Hz."""
    buf = io.BytesIO(audio_bytes)
    try:
        audio_np, _ = librosa.load(buf, sr=sr, mono=True)
    except Exception as e:
        raise HTTPException(400, f"failed to decode audio: {e}")
    return audio_np


def _asr_transcribe_sync(audio_np: np.ndarray, hotwords: Optional[str] = None) -> dict:
    """Run VibeVoice-ASR on a single audio array (float32, 24kHz, mono).

    Args:
        audio_np: float32 mono audio at 24kHz
        hotwords: optional comma-separated domain terms (names, technical jargon)
                  to bias recognition. The processor embeds them in the prompt
                  as "with extra info: {hotwords}".

    Returns dict with keys: text, segments (list of dicts), generation_s.
    """
    if asr_model is None or asr_processor is None:
        raise HTTPException(503, "ASR model not loaded")

    inputs = asr_processor(
        audio=[audio_np],
        sampling_rate=None,
        return_tensors="pt",
        padding=True,
        add_generation_prompt=True,
        context_info=hotwords if hotwords and hotwords.strip() else None,
    )

    def _to_dev(v):
        if isinstance(v, torch.Tensor):
            v = v.to("cuda")
            if v.dtype == torch.float32:
                v = v.to(torch.bfloat16)
        return v
    inputs = {k: _to_dev(v) for k, v in inputs.items()}

    gen_cfg = {
        "max_new_tokens": 2048,
        "do_sample": False,
        "num_beams": 1,
        "pad_token_id": asr_processor.pad_id,
        "eos_token_id": asr_processor.tokenizer.eos_token_id,
    }

    t0 = time.time()
    with torch.no_grad():
        out = asr_model.generate(**inputs, **gen_cfg)
    gen_s = time.time() - t0

    in_len = inputs["input_ids"].shape[1]
    gen_ids = out[0, in_len:]
    eos_pos = (gen_ids == asr_processor.tokenizer.eos_token_id).nonzero(as_tuple=True)[0]
    if len(eos_pos) > 0:
        gen_ids = gen_ids[: eos_pos[0] + 1]
    raw = asr_processor.decode(gen_ids, skip_special_tokens=True)
    try:
        segments = asr_processor.post_process_transcription(raw)
    except Exception:
        segments = []

    full_text = " ".join(s.get("text", "") for s in segments).strip()
    if not full_text and raw:
        # fallback: strip "assistant\n" prefix the model emits
        full_text = raw.replace("assistant\n", "").strip()
    return {"text": full_text, "segments": segments, "generation_s": gen_s, "raw": raw}


# ============================================================
# LLM (Qwen2.5-Instruct) — used by the conversation endpoint
# ============================================================
# Cached prefill of the system prompt. Built once at startup and reused
# across every conversation turn that begins with the same system prompt.
# Skips ~150-300 tokens of prefill per turn → measurable TTFA reduction.
_llm_system_cache: Optional[dict] = None


def _build_system_prefill_cache(system_prompt: str) -> Optional[dict]:
    """Pre-compute KV cache for the system prompt so we never re-prefill it."""
    if llm_model is None or llm_tokenizer is None:
        return None
    try:
        sys_text = llm_tokenizer.apply_chat_template(
            [{"role": "system", "content": system_prompt}],
            tokenize=False,
            add_generation_prompt=False,
        )
        sys_ids = llm_tokenizer(sys_text, return_tensors="pt").to("cuda")
        with torch.no_grad():
            out = llm_model(**sys_ids, use_cache=True)
        return {
            "system_prompt": system_prompt,
            "input_ids": sys_ids["input_ids"],
            "past_key_values": out.past_key_values,
            "tokens": sys_ids["input_ids"].shape[1],
        }
    except Exception as e:
        print(f"[llm-prefill] cache build failed: {e}")
        return None


_DIACRITIZE_SYSTEM = (
    "أنت مدقق لغوي عربي محترف. مهمتك: شكّل النص العربي التالي بالتشكيل "
    "الكامل (الفتحة، الضمة، الكسرة، السكون، الشدّة، التنوين) بدقة عالية، "
    "وأضف علامات الترقيم المناسبة (نقطة، فاصلة) إذا كانت مفقودة. "
    "أعد النص المُشَكَّل فقط بدون أي شرح أو مقدّمة أو علامات اقتباس."
)


# Tiny in-memory LRU for diacritized text — repeat TTS calls with the same
# article shouldn't pay the LLM cost twice.
_diacritize_cache: dict[str, str] = {}
_DIACRITIZE_CACHE_LIMIT = 256


def _diacritize_arabic(text: str, max_chars: int = 1500) -> str:
    """Add Arabic diacritics + light punctuation cleanup using Qwen.

    Cost: ~300-1500 ms per call depending on length. Caller decides whether
    the latency is worth the quality bump. Cached so repeat calls are free.
    """
    if not text or not text.strip():
        return text
    cache_key = text[:max_chars]
    if cache_key in _diacritize_cache:
        return _diacritize_cache[cache_key]
    if llm_model is None or llm_tokenizer is None:
        return text
    try:
        # Truncate input to keep generation bounded.
        prompt_text = text[:max_chars]
        messages = [
            {"role": "system", "content": _DIACRITIZE_SYSTEM},
            {"role": "user", "content": prompt_text},
        ]
        # Generous max_new_tokens because diacritics inflate token count.
        out = _llm_generate_sync(messages, max_new_tokens=int(len(prompt_text) * 2.5) + 64)
        out = out.strip().strip('"').strip("'").strip("«").strip("»").strip()
        # Sanity check: if output is empty or way shorter than input, fall back
        if not out or len(out) < len(prompt_text) * 0.4:
            return text
        if len(_diacritize_cache) >= _DIACRITIZE_CACHE_LIMIT:
            _diacritize_cache.pop(next(iter(_diacritize_cache)))
        _diacritize_cache[cache_key] = out
        # If we truncated, append the rest unchanged
        if len(text) > max_chars:
            out = out + text[max_chars:]
        return out
    except Exception as e:
        print(f"[diacritize] failed, returning original: {e}")
        return text


def _llm_generate_sync(messages: list[dict], max_new_tokens: int = 256) -> str:
    """Run Qwen on a chat-formatted message list and return assistant text.

    If `messages[0]` is a system message that matches the cached prefill,
    we reuse the precomputed KV cache and only feed the (much shorter)
    user/assistant turns through the prefill — saves ~50-150 ms per turn.
    """
    if llm_model is None or llm_tokenizer is None:
        raise HTTPException(503, "LLM not loaded")

    cache = _llm_system_cache
    can_reuse = (
        cache is not None
        and len(messages) >= 1
        and messages[0].get("role") == "system"
        and messages[0].get("content") == cache.get("system_prompt")
    )

    if can_reuse:
        # Build only the dialog after the system message, then concat ids.
        dialog_text = llm_tokenizer.apply_chat_template(
            messages[1:], tokenize=False, add_generation_prompt=True
        )
        dialog_ids = llm_tokenizer(
            dialog_text, return_tensors="pt", add_special_tokens=False
        ).to("cuda")
        # We pass full input_ids so HuggingFace .generate() can correctly
        # build the position ids etc., plus the cached KV via past_key_values.
        full_ids = torch.cat([cache["input_ids"], dialog_ids["input_ids"]], dim=1)
        # IMPORTANT: clone the KV cache — .generate() appends turn KVs to
        # `past_key_values` in place, which would pollute the shared cache
        # for the next turn. Cloning is fast (just GPU memcpy of small tensors).
        try:
            import copy as _copy
            pkv_clone = _copy.deepcopy(cache["past_key_values"])
            with torch.no_grad():
                out = llm_model.generate(
                    input_ids=full_ids,
                    past_key_values=pkv_clone,
                    max_new_tokens=max_new_tokens,
                    do_sample=True,
                    temperature=0.7,
                    top_p=0.9,
                    repetition_penalty=1.05,
                    pad_token_id=llm_tokenizer.eos_token_id,
                )
            new_ids = out[0, full_ids.shape[1]:]
            return llm_tokenizer.decode(new_ids, skip_special_tokens=True).strip()
        except Exception as e:
            # If anything goes wrong with the cached path, fall back to cold.
            print(f"[llm-prefill] reuse failed, falling back: {e}")
            # fall through to cold path

    # Cold path: full prefill of the whole chat.
    chat = llm_tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    inputs = llm_tokenizer(chat, return_tensors="pt").to("cuda")
    with torch.no_grad():
        out = llm_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.05,
            pad_token_id=llm_tokenizer.eos_token_id,
        )
    new_ids = out[0, inputs["input_ids"].shape[1]:]
    return llm_tokenizer.decode(new_ids, skip_special_tokens=True).strip()


# ============================================================
# Lifespan
# ============================================================
@asynccontextmanager
async def lifespan(app: FastAPI):
    global processor, model, _tts_lock, _asr_lock, _llm_lock
    # Locks must be created on the running event loop, not at import time.
    _tts_lock = asyncio.Lock()
    _asr_lock = asyncio.Lock()
    _llm_lock = asyncio.Lock()
    print(f"[startup] loading {MODEL_NAME} with flash_attention_2...")
    t0 = time.time()
    from vibevoice.modular.modeling_vibevoice_inference import VibeVoiceForConditionalGenerationInference
    from vibevoice.processor.vibevoice_processor import VibeVoiceProcessor
    processor = VibeVoiceProcessor.from_pretrained(MODEL_NAME)
    model = VibeVoiceForConditionalGenerationInference.from_pretrained(
        MODEL_NAME, torch_dtype=torch.bfloat16, device_map="cuda",
        attn_implementation="flash_attention_2",
    )
    model.eval()
    model.set_ddpm_inference_steps(num_steps=DIFFUSION_STEPS)
    print(f"[startup] loaded in {time.time()-t0:.1f}s, GPU mem={torch.cuda.memory_allocated()/1e9:.1f}GB")

    # auto-discover voices on disk
    for f in os.listdir(VOICES_DIR):
        if f.endswith(".wav"):
            try: _load_voice_from_disk(f[:-4])
            except Exception as e: print(f"  failed to load {f}: {e}")

    if "default" not in voice_profiles and os.path.exists(DEFAULT_REF):
        audio_np, _ = librosa.load(DEFAULT_REF, sr=SAMPLE_RATE)
        _save_voice("default", audio_np, "Default", "ar")

    print(f"[startup] voices loaded: {len(voice_profiles)} ({list(voice_profiles.keys())[:5]}...)")
    print(f"[startup] auth: {'enabled' if API_KEY else 'DISABLED (set MV_API_KEY env to enable)'}")

    # warmup TTS
    try:
        _ = _generate_full("مرحبا", "default" if "default" in voice_profiles else next(iter(voice_profiles)))
        print("[startup] TTS warmup done")
    except Exception as e:
        print(f"[startup] TTS warmup error: {e}")

    # load ASR (VibeVoice-ASR) — same family as Large, supports 50+ languages incl. ar
    if ASR_ENABLED:
        global asr_processor, asr_model
        try:
            from vibevoice.modular.modeling_vibevoice_asr import VibeVoiceASRForConditionalGeneration
            from vibevoice.processor.vibevoice_asr_processor import VibeVoiceASRProcessor
            print(f"[startup] loading ASR {ASR_MODEL_NAME} with flash_attention_2...")
            t0 = time.time()
            asr_processor = VibeVoiceASRProcessor.from_pretrained(
                ASR_MODEL_NAME, language_model_pretrained_name="Qwen/Qwen2.5-7B"
            )
            asr_model = VibeVoiceASRForConditionalGeneration.from_pretrained(
                ASR_MODEL_NAME,
                dtype=torch.bfloat16,
                attn_implementation="flash_attention_2",
                trust_remote_code=True,
            )
            asr_model = asr_model.to(torch.bfloat16).to("cuda")
            asr_model.config.torch_dtype = torch.bfloat16  # encode_speech reads this
            asr_model.eval()
            print(f"[startup] ASR loaded in {time.time()-t0:.1f}s, "
                  f"GPU mem total={torch.cuda.memory_allocated()/1e9:.1f}GB")
            # warmup ASR on a tiny silent buffer to compile graphs
            try:
                _silent = np.zeros(int(0.5 * ASR_SAMPLE_RATE), dtype=np.float32)
                _ = _asr_transcribe_sync(_silent)
                print("[startup] ASR warmup done")
            except Exception as e:
                print(f"[startup] ASR warmup error: {e}")
        except Exception as e:
            print(f"[startup] ASR DISABLED — load failed: {e}")
            asr_processor = None
            asr_model = None
    else:
        print("[startup] ASR disabled via MV_ASR_ENABLED=0")

    # load LLM (Qwen2.5-Instruct) for the conversation endpoint
    if LLM_ENABLED:
        global llm_model, llm_tokenizer
        try:
            from transformers import AutoModelForCausalLM, AutoTokenizer
            print(f"[startup] loading LLM {LLM_MODEL_NAME} with flash_attention_2...")
            t0 = time.time()
            llm_tokenizer = AutoTokenizer.from_pretrained(LLM_MODEL_NAME)
            llm_model = AutoModelForCausalLM.from_pretrained(
                LLM_MODEL_NAME,
                torch_dtype=torch.bfloat16,
                attn_implementation="flash_attention_2",
                device_map="cuda",
            )
            llm_model.eval()
            print(f"[startup] LLM loaded in {time.time()-t0:.1f}s, "
                  f"GPU mem total={torch.cuda.memory_allocated()/1e9:.1f}GB")
            # warmup with a tiny prompt
            try:
                _ = _llm_generate_sync(
                    [{"role": "user", "content": "مرحبا"}], max_new_tokens=8
                )
                print("[startup] LLM warmup done")
            except Exception as e:
                print(f"[startup] LLM warmup error: {e}")
            # Pre-cache the system prompt KV so every conversation turn
            # skips re-prefilling the same ~150 system-prompt tokens.
            global _llm_system_cache
            _llm_system_cache = _build_system_prefill_cache(DEFAULT_SYSTEM_PROMPT)
            if _llm_system_cache is not None:
                print(f"[startup] LLM system-prompt KV cache ready "
                      f"({_llm_system_cache['tokens']} tokens)")
        except Exception as e:
            print(f"[startup] LLM DISABLED — load failed: {e}")
            llm_model = None
            llm_tokenizer = None
    else:
        print("[startup] LLM disabled via MV_LLM_ENABLED=0")

    yield


# ============================================================
# App
# ============================================================
app = FastAPI(
    title="Mostashar Voice API",
    description="Real-time Arabic voice cloning + TTS. ElevenLabs-style REST API. "
                "Auth via `xi-api-key` header (or `Authorization: Bearer ...`). "
                "Set MV_API_KEY env to enable; left empty disables auth (development).",
    version="1.0.0",
    lifespan=lifespan,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], allow_methods=["*"], allow_headers=["*"],
)


# ============================================================
# Health
# ============================================================
@app.get("/v1/health", response_model=HealthResponse, tags=["misc"])
async def health():
    return HealthResponse(
        status="ok",
        model=MODEL_NAME,
        diffusion_steps=DIFFUSION_STEPS,
        voices_count=len(voice_profiles),
        gpu_mem_gb=round(torch.cuda.memory_allocated() / 1e9, 2),
        version="1.0.0",
        asr_loaded=asr_model is not None,
        asr_model=ASR_MODEL_NAME if asr_model is not None else None,
        llm_loaded=llm_model is not None,
        llm_model=LLM_MODEL_NAME if llm_model is not None else None,
    )


@app.get("/health", include_in_schema=False)
async def health_legacy(): return await health()


@app.get("/v1/queue-status", tags=["misc"])
async def queue_status(_=Depends(require_api_key)):
    """Live concurrency snapshot per model. Useful for monitoring + debugging.

    `queued`: requests waiting for the model.
    `running`: 1 if a request is using the model right now, else 0.
    `served`: cumulative requests completed since startup.
    `avg_wait_ms`: mean queue wait time across served requests.
    `avg_run_ms`: mean GPU time across served requests.
    """
    return {
        "tts": _tts_stats.snapshot(),
        "asr": _asr_stats.snapshot(),
        "llm": _llm_stats.snapshot(),
    }


# ============================================================
# Models
# ============================================================
@app.get("/v1/models", response_model=list[ModelInfo], tags=["models"])
async def list_models(_=Depends(require_api_key)):
    models = [
        ModelInfo(
            model_id="vibevoice-large",
            name="VibeVoice Large (8B) — TTS",
            languages=["ar", "en", "multilingual"],
            can_clone=True,
            description="Premium quality voice cloning. ~334ms TTFA streaming.",
        ),
    ]
    if llm_model is not None:
        models.append(ModelInfo(
            model_id=LLM_MODEL_NAME.split("/")[-1].lower(),
            name=f"{LLM_MODEL_NAME} (chat backbone for /v1/conversation/ws)",
            languages=["ar", "en", "multi"],
            can_clone=False,
            description="Drives the live conversation endpoint with chat-completion semantics.",
        ))
    if asr_model is not None:
        models.append(ModelInfo(
            model_id="vibevoice-asr",
            name="VibeVoice ASR — Speech-to-Text",
            languages=["ar", "en", "zh", "es", "pt", "de", "ja", "ko", "fr", "ru",
                       "id", "sv", "it", "he", "nl", "pl", "no", "tr", "th", "hu",
                       "ca", "cs", "da", "fa", "af", "hi", "fi", "et", "el", "ro",
                       "vi", "bg", "is", "sl", "sk", "lt", "sw", "uk", "lv", "hr",
                       "ne", "sr", "tl", "yi", "ms", "ur", "mn", "hy", "jv", "kl",
                       "aa"],
            can_clone=False,
            description="60-min single-pass STT with diarization, timestamps, hotwords. RTF~0.06.",
        ))
    return models


# ============================================================
# Voices
# ============================================================
@app.get("/v1/voices", response_model=VoicesListResponse, tags=["voices"])
async def list_voices(_=Depends(require_api_key)):
    voices = []
    for vid, p in voice_profiles.items():
        voices.append(VoiceMeta(
            voice_id=vid,
            name=p.get("name", vid),
            language=p.get("language", "ar"),
            dur_s=round(p.get("ref_audio_dur_s", 0), 2),
            preview_url=f"/v1/voices/{vid}/preview",
            created_at=p.get("created_at"),
        ))
    voices.sort(key=lambda v: -(v.created_at or 0))
    return VoicesListResponse(voices=voices)


@app.get("/v1/voices/{voice_id}", response_model=VoiceMeta, tags=["voices"])
async def get_voice(voice_id: str = PathParam(...), _=Depends(require_api_key)):
    p = _get_voice(voice_id)
    return VoiceMeta(
        voice_id=p["voice_id"], name=p["name"], language=p["language"],
        dur_s=round(p["ref_audio_dur_s"], 2),
        preview_url=f"/v1/voices/{voice_id}/preview",
        created_at=p.get("created_at"),
    )


@app.get("/v1/voices/{voice_id}/preview", tags=["voices"])
async def voice_preview(voice_id: str, _=Depends(require_api_key)):
    _get_voice(voice_id)  # ensures it's loaded / 404 if missing
    return FileResponse(_wav_path(voice_id), media_type="audio/wav")


@app.post("/v1/voices/add", response_model=CloneResponse, tags=["voices"])
async def add_voice(
    name: str = Form(..., min_length=1, max_length=80),
    language: str = Form("ar", pattern="^(ar|en|multi)$"),
    start_s: float = Form(0.0, ge=0),
    end_s: float = Form(30.0, gt=0, le=300),
    files: list[UploadFile] = File(..., description="One audio file (mp3/wav/m4a/webm)"),
    _=Depends(require_api_key),
):
    if not files:
        raise HTTPException(400, "no audio file provided")
    audio = files[0]
    audio_bytes = await audio.read()
    try:
        buf = io.BytesIO(audio_bytes)
        audio_np, _sr = librosa.load(buf, sr=SAMPLE_RATE)
    except Exception as e:
        raise HTTPException(400, f"failed to decode audio: {e}")

    s0 = max(0, int(start_s * SAMPLE_RATE))
    s1 = min(len(audio_np), int(end_s * SAMPLE_RATE))
    if s1 - s0 < 3 * SAMPLE_RATE:
        raise HTTPException(400, "selection must be at least 3 seconds")
    audio_np = audio_np[s0:s1]
    if len(audio_np) > 30 * SAMPLE_RATE:
        audio_np = audio_np[: 30 * SAMPLE_RATE]

    voice_id = f"{_slugify(name)}-{uuid.uuid4().hex[:6]}"
    profile = _save_voice(voice_id, audio_np, name, language)
    return CloneResponse(
        voice_id=voice_id, name=name, language=language,
        dur_s=round(profile["ref_audio_dur_s"], 2),
    )


@app.post("/v1/voices/{voice_id}/clean", response_model=VoiceMeta, tags=["voices"])
async def clean_voice(voice_id: str, _=Depends(require_api_key)):
    """Re-run the denoiser on this voice's reference audio in-place.

    Use this on legacy voices that were uploaded before the denoiser
    was added (e.g. the original edge-tts premades). After cleaning,
    the in-memory profile is reloaded so subsequent TTS calls pick
    up the cleaner reference.
    """
    profile = _get_voice(voice_id)
    audio = profile["ref_audio_np"]
    cleaned = _denoise_audio(audio, SAMPLE_RATE)
    sf.write(_wav_path(voice_id), cleaned, SAMPLE_RATE)
    # Update on-disk metadata
    meta = {}
    mp = _meta_path(voice_id)
    if os.path.exists(mp):
        try:
            meta = json.load(open(mp, encoding="utf-8"))
        except Exception:
            meta = {}
    meta["denoised"] = True
    meta["denoised_at"] = int(time.time())
    with open(mp, "w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)
    # Reload in-memory profile so the next TTS uses the cleaned audio
    voice_profiles.pop(voice_id, None)
    p = _load_voice_from_disk(voice_id)
    return VoiceMeta(
        voice_id=voice_id,
        name=p["name"] if p else voice_id,
        language=p["language"] if p else "ar",
        dur_s=round(p["ref_audio_dur_s"], 2) if p else 0,
        preview_url=f"/v1/voices/{voice_id}/preview",
        created_at=p.get("created_at") if p else None,
    )


@app.post("/v1/voices/clean-all", tags=["voices"])
async def clean_all_voices(_=Depends(require_api_key)):
    """Bulk-denoise every voice in the library that hasn't been cleaned yet.

    Skips voices whose metadata already has `denoised: true`.
    Returns a per-voice summary.
    """
    results = []
    for vid in list(voice_profiles.keys()):
        meta_p = _meta_path(vid)
        meta = {}
        if os.path.exists(meta_p):
            try:
                meta = json.load(open(meta_p, encoding="utf-8"))
            except Exception:
                meta = {}
        if meta.get("denoised"):
            results.append({"voice_id": vid, "skipped": "already denoised"})
            continue
        try:
            audio = voice_profiles[vid]["ref_audio_np"]
            cleaned = _denoise_audio(audio, SAMPLE_RATE)
            sf.write(_wav_path(vid), cleaned, SAMPLE_RATE)
            meta["denoised"] = True
            meta["denoised_at"] = int(time.time())
            with open(meta_p, "w", encoding="utf-8") as f:
                json.dump(meta, f, ensure_ascii=False, indent=2)
            voice_profiles.pop(vid, None)
            _load_voice_from_disk(vid)
            results.append({"voice_id": vid, "ok": True})
        except Exception as e:
            results.append({"voice_id": vid, "error": str(e)[:200]})
    return {"cleaned": results}


@app.delete("/v1/voices/{voice_id}", tags=["voices"])
async def delete_voice(voice_id: str, _=Depends(require_api_key)):
    if voice_id == "default":
        raise HTTPException(403, "cannot delete default voice")
    if voice_id in voice_profiles:
        del voice_profiles[voice_id]
    for path in (_wav_path(voice_id), _meta_path(voice_id)):
        if os.path.exists(path):
            os.remove(path)
    return {"ok": True, "voice_id": voice_id}


# ============================================================
# Text-to-Speech
# ============================================================
@app.post("/v1/text-to-speech/{voice_id}", tags=["tts"], responses={
    200: {"content": {"audio/wav": {}}, "description": "Full WAV audio"},
})
async def tts_full(
    voice_id: str,
    req: TTSRequest,
    _=Depends(require_api_key),
):
    """Generate the full audio (non-streaming). Returns WAV file."""
    loop = asyncio.get_event_loop()
    text = req.text
    if req.auto_diacritize:
        assert _llm_lock is not None
        async with _serialize(_llm_lock, _llm_stats):
            text = await loop.run_in_executor(None, _diacritize_arabic, text)
    assert _tts_lock is not None
    async with _serialize(_tts_lock, _tts_stats):
        audio = await loop.run_in_executor(
            None, _generate_full, text, voice_id, req.voice_settings
        )
    a16 = (np.clip(audio, -1.0, 1.0) * 32767).astype(np.int16)
    body = _wav_header(len(a16)) + a16.tobytes()
    return Response(content=body, media_type="audio/wav")


@app.post("/v1/text-to-speech/{voice_id}/stream", tags=["tts"])
async def tts_stream(
    voice_id: str,
    req: TTSRequest,
    _=Depends(require_api_key),
):
    """Streaming TTS via HTTP chunked transfer encoding.

    output_format=pcm_24000 → raw PCM16LE 24kHz mono chunks (Content-Type: audio/pcm)
    output_format=wav       → WAV header + chunked PCM (Content-Type: audio/wav)
    """
    request_start = time.time()
    is_wav = req.output_format == "wav"
    media_type = "audio/wav" if is_wav else "audio/pcm"

    # Resolve diacritization BEFORE the response stream begins so the
    # latency is paid up-front (rather than mysteriously delaying TTFA
    # while the caller is already subscribed to chunks).
    text = req.text
    if req.auto_diacritize:
        loop = asyncio.get_event_loop()
        assert _llm_lock is not None
        async with _serialize(_llm_lock, _llm_stats):
            text = await loop.run_in_executor(None, _diacritize_arabic, text)

    async def generator():
        if is_wav:
            yield _wav_streaming_header(SAMPLE_RATE)
        first_emitted = False
        assert _tts_lock is not None
        async with _serialize(_tts_lock, _tts_stats):
            async for chunk in _generate_stream(text, voice_id, req.voice_settings):
                if not first_emitted:
                    ttfa_ms = (time.time() - request_start) * 1000
                    print(f"[tts_stream] voice={voice_id} TTFA={ttfa_ms:.0f}ms")
                    first_emitted = True
                yield chunk

    headers = {
        "X-Sample-Rate": str(SAMPLE_RATE),
        "X-Audio-Format": "pcm_s16le",
        "Cache-Control": "no-cache",
    }
    return StreamingResponse(generator(), media_type=media_type, headers=headers)


# ============================================================
# Multi-Speaker Dialogue
# ============================================================
@app.post("/v1/dialogue", tags=["tts"], responses={
    200: {"content": {"audio/wav": {}}, "description": "Full WAV audio of the dialogue"},
})
async def dialogue(req: DialogueRequest, _=Depends(require_api_key)):
    """Generate a multi-speaker dialogue (e.g. role-play, podcast, training scenario).

    Up to 4 distinct voices in one continuous audio file with natural turn-taking.
    Specify each line by speaker index (1-based) and text.

    Example body:
        {
          "speakers": ["hamed_saudi", "salma_egypt"],
          "lines": [
            {"speaker": 1, "text": "السلام عليكم. كيف يمكنني مساعدتك؟"},
            {"speaker": 2, "text": "أريد فتح حساب جديد من فضلك."},
            {"speaker": 1, "text": "بكل سرور. دعنا نبدأ."}
          ]
        }
    """
    loop = asyncio.get_event_loop()
    assert _tts_lock is not None
    async with _serialize(_tts_lock, _tts_stats):
        audio = await loop.run_in_executor(
            None, lambda: _generate_dialogue(req.lines, req.speakers, req.voice_settings)
        )
    a16 = (np.clip(audio, -1.0, 1.0) * 32767).astype(np.int16)
    if req.output_format == "wav":
        body = _wav_header(len(a16)) + a16.tobytes()
        return Response(content=body, media_type="audio/wav")
    # raw PCM16LE
    return Response(content=a16.tobytes(), media_type="audio/pcm")


# ============================================================
# Speech-to-Text (VibeVoice-ASR)
# ============================================================
@app.post("/v1/speech-to-text", response_model=STTResponse, tags=["stt"])
async def speech_to_text(
    file: UploadFile = File(..., description="Audio file (mp3/wav/m4a/webm/ogg)"),
    language: str = Form("ar"),
    hotwords: Optional[str] = Form(
        None,
        description='Comma-separated domain terms to bias recognition (e.g. "أرامكو, STC, Kubernetes")',
    ),
    _=Depends(require_api_key),
):
    """Simple STT — returns plain transcribed text. ElevenLabs-compatible shape.

    For diarization + timestamps + structured output use `/v1/transcribe`.
    """
    if asr_model is None:
        raise HTTPException(503, "ASR not available on this server")
    audio_bytes = await file.read()
    audio_np = _decode_audio_bytes(audio_bytes)
    if len(audio_np) < 0.1 * ASR_SAMPLE_RATE:
        raise HTTPException(400, "audio too short (<100ms)")
    loop = asyncio.get_event_loop()
    assert _asr_lock is not None
    async with _serialize(_asr_lock, _asr_stats):
        result = await loop.run_in_executor(None, _asr_transcribe_sync, audio_np, hotwords)
    return STTResponse(
        text=result["text"],
        language=language,
        duration_s=round(len(audio_np) / ASR_SAMPLE_RATE, 2),
    )


@app.post("/v1/transcribe", response_model=TranscribeResponse, tags=["stt"])
async def transcribe(
    file: UploadFile = File(..., description="Audio file (mp3/wav/m4a/webm/ogg)"),
    language: str = Form("ar"),
    hotwords: Optional[str] = Form(
        None,
        description='Comma-separated domain terms to bias recognition (e.g. "أرامكو, STC, Kubernetes")',
    ),
    _=Depends(require_api_key),
):
    """Full transcription with diarization (who), timestamps (when), and content (what).

    Uses VibeVoice-ASR's structured-JSON output. Up to 60 minutes single-pass.
    Pass `hotwords` to lift recognition accuracy on domain-specific names/terms.
    """
    if asr_model is None:
        raise HTTPException(503, "ASR not available on this server")
    audio_bytes = await file.read()
    audio_np = _decode_audio_bytes(audio_bytes)
    if len(audio_np) < 0.1 * ASR_SAMPLE_RATE:
        raise HTTPException(400, "audio too short (<100ms)")
    loop = asyncio.get_event_loop()
    assert _asr_lock is not None
    async with _serialize(_asr_lock, _asr_stats):
        result = await loop.run_in_executor(None, _asr_transcribe_sync, audio_np, hotwords)
    segs = [
        TranscriptSegment(
            start_time=float(s.get("start_time", 0.0)),
            end_time=float(s.get("end_time", 0.0)),
            speaker_id=int(s.get("speaker_id", 0)),
            text=str(s.get("text", "")),
        )
        for s in result["segments"]
    ]
    speakers_count = len({s.speaker_id for s in segs}) if segs else 0
    return TranscribeResponse(
        text=result["text"],
        language=language,
        duration_s=round(len(audio_np) / ASR_SAMPLE_RATE, 2),
        speakers_count=speakers_count,
        segments=segs,
        generation_ms=round(result["generation_s"] * 1000, 0),
    )


# ============================================================
# Live Conversation (Speech-to-Speech)
# ============================================================
@app.websocket("/v1/conversation/ws")
async def conversation_ws(ws: WebSocket):
    """Bidirectional voice agent over WebSocket.

    Auth: ?api_key=... query param (since WS can't set headers).
    Optional query params:
      - voice_id (default "default")
      - language (default "ar")

    Client → Server protocol:
      - Binary frames: PCM16LE @ 16 kHz mono mic chunks
      - JSON `{"type":"end_of_utterance"}`: triggers ASR → LLM → TTS pipeline
      - JSON `{"type":"reset"}`: clears conversation history
      - JSON `{"type":"system","content":"..."}`: override system prompt
      - JSON `{"type":"interrupt"}`: stop current TTS playback (server discards
        any in-flight audio for the current turn)
      - JSON `{"type":"text","content":"..."}`: bypass ASR, send text directly

    Server → Client protocol:
      - JSON `{"type":"ready"}`: handshake complete
      - JSON `{"type":"transcript","text":"..."}`: STT finished
      - JSON `{"type":"response_text","text":"..."}`: LLM finished
      - JSON `{"type":"audio_meta","sample_rate":24000,"format":"pcm_s16le"}`
      - Binary frames: PCM16LE @ 24 kHz TTS chunks
      - JSON `{"type":"turn_done","ttfa_ms":N,"total_ms":N}`
      - JSON `{"type":"error","message":"..."}`
    """
    if API_KEY:
        token = ws.query_params.get("api_key", "")
        if token != API_KEY:
            await ws.close(code=1008)
            return

    voice_id = ws.query_params.get("voice_id", "default")
    language = ws.query_params.get("language", "ar")

    if asr_model is None:
        await ws.close(code=1011)
        return
    if llm_model is None:
        await ws.close(code=1011)
        return

    await ws.accept()
    await ws.send_json({"type": "ready", "voice_id": voice_id, "language": language})

    audio_buffer = bytearray()
    history: list[dict] = [
        {"role": "system", "content": DEFAULT_SYSTEM_PROMPT}
    ]
    interrupt_flag = {"value": False}
    # Allow client to resume by passing ?session_id= — otherwise mint a new one.
    requested_sid = ws.query_params.get("session_id", "")
    session_id = requested_sid or f"sess-{int(time.time())}-{uuid.uuid4().hex[:6]}"
    session_log = SessionLog(session_id)
    await ws.send_json({"type": "session", "session_id": session_id})

    try:
        while True:
            msg = await ws.receive()
            if msg.get("type") == "websocket.disconnect":
                break

            if "bytes" in msg and msg["bytes"] is not None:
                audio_buffer.extend(msg["bytes"])
                continue

            text_msg = msg.get("text")
            if not text_msg:
                continue
            try:
                data = json.loads(text_msg)
            except Exception:
                continue

            mtype = data.get("type")
            if mtype == "reset":
                history = [{"role": "system", "content": DEFAULT_SYSTEM_PROMPT}]
                audio_buffer.clear()
                await ws.send_json({"type": "ready"})
            elif mtype == "system":
                history = [{"role": "system", "content": data.get("content", "")}]
            elif mtype == "interrupt":
                interrupt_flag["value"] = True
            elif mtype == "text":
                user_text = (data.get("content") or "").strip()
                if user_text:
                    interrupt_flag["value"] = False
                    await _conversation_turn(ws, voice_id, language, user_text, history, interrupt_flag)
            elif mtype == "end_of_utterance":
                if not audio_buffer:
                    continue
                interrupt_flag["value"] = False
                pcm = bytes(audio_buffer)
                audio_buffer.clear()

                # PCM16LE 16kHz mono → float32. Gemma 4 wants 16 kHz directly,
                # so we keep that rate when delegating to the sidecar. Only
                # resample to 24 kHz when falling back to VibeVoice-ASR.
                audio_i16 = np.frombuffer(pcm, dtype=np.int16)
                audio_f32_16k = audio_i16.astype(np.float32) / 32768.0

                if len(audio_f32_16k) < 0.2 * INPUT_SAMPLE_RATE:
                    await ws.send_json({"type": "error", "message": "audio too short"})
                    continue

                # Always run VibeVoice-ASR in PARALLEL with Gemma 4. Two
                # different models on different memory regions of the same GPU
                # ⇒ they overlap with no extra wall-clock cost, and we get
                # back BOTH the real transcript (for the UI + chat history)
                # AND Gemma's response in one round-trip. If Gemma 4 fails,
                # the transcript is already in hand and we hand off to Qwen.
                audio_f32_24k = librosa.resample(
                    audio_f32_16k, orig_sr=INPUT_SAMPLE_RATE,
                    target_sr=ASR_SAMPLE_RATE,
                )

                async def _run_asr():
                    assert _asr_lock is not None
                    # Cap to <60 s so we never hit the streaming code path
                    # in the patched community fork (which crashes with
                    # "unexpected keyword argument"). Keeps the LATEST
                    # window so the user still sees what they just said.
                    asr_audio = audio_f32_24k
                    if len(asr_audio) > ASR_MAX_AUDIO_SAMPLES:
                        asr_audio = asr_audio[-ASR_MAX_AUDIO_SAMPLES:]
                    try:
                        async with _serialize(_asr_lock, _asr_stats):
                            loop = asyncio.get_event_loop()
                            return await loop.run_in_executor(
                                None, _asr_transcribe_sync, asr_audio
                            )
                    except Exception as e:
                        # ASR is best-effort here — Gemma 4 carries the
                        # actual response. Don't break the conversation.
                        print(f"[asr] failed in conversation: {e}")
                        return {"text": "", "segments": []}

                async def _run_gemma():
                    if not GEMMA4_URL:
                        return None
                    try:
                        return await _gemma4_audio_chat(audio_f32_16k, history)
                    except Exception as e:
                        print(f"[conversation] Gemma 4 failed: {e}")
                        return None

                # Save the audio to disk for recovery / replay.
                turn_idx = session_log.next_turn_idx()
                audio_path = session_log.save_audio(turn_idx, audio_f32_16k, INPUT_SAMPLE_RATE)

                asr_task = asyncio.create_task(_run_asr())
                gemma_task = asyncio.create_task(_run_gemma())
                stt_result, gemma_response = await asyncio.gather(asr_task, gemma_task)

                user_text_raw = (stt_result.get("text") or "").strip()
                user_text = _clean_asr_text_for_display(user_text_raw)
                # Show the CLEANED transcript in the UI — the [Silence] /
                # [Unintelligible Speech] markers are internal ASR noise
                # and confuse / clutter the chat bubble.
                if user_text:
                    await ws.send_json({"type": "transcript", "text": user_text})

                if not user_text:
                    # Couldn't make sense of the audio at all
                    session_log.record_turn(turn_idx, audio_path, "", "")
                    continue

                if gemma_response and _looks_arabic(gemma_response):
                    # Gemma succeeded — use its response, but store the REAL
                    # transcript in history (so the next turn's context is
                    # actual text, not a "[audio]" placeholder).
                    session_log.record_turn(turn_idx, audio_path, user_text_raw, gemma_response)
                    await _conversation_turn_with_response(
                        ws, voice_id, language, user_text, gemma_response,
                        history, interrupt_flag,
                    )
                else:
                    # Gemma failed or drifted — fall back to Qwen using the
                    # already-computed transcript.
                    response_text = await _conversation_turn(
                        ws, voice_id, language, user_text, history, interrupt_flag,
                    )
                    session_log.record_turn(turn_idx, audio_path, user_text_raw, response_text or "")
    except WebSocketDisconnect:
        pass
    except Exception as e:
        import traceback
        traceback.print_exc()
        try:
            await ws.send_json({"type": "error", "message": str(e)[:500]})
        except Exception:
            pass


async def _gemma4_audio_chat(audio_f32_16k: np.ndarray, history: list[dict]) -> str:
    """POST audio to the Gemma 4 sidecar, return the assistant's text reply.

    Raises on any non-200 response so the caller can fall back to ASR+LLM.
    """
    import httpx
    import io as _io
    buf = _io.BytesIO()
    sf.write(buf, audio_f32_16k, INPUT_SAMPLE_RATE, format="WAV", subtype="PCM_16")
    buf.seek(0)
    # Strip the system message — sidecar adds its own. Keep prior dialog only.
    dialog = [t for t in history if t.get("role") in ("user", "assistant")]
    files = {"file": ("audio.wav", buf.getvalue(), "audio/wav")}
    data = {"history": json.dumps(dialog, ensure_ascii=False), "max_tokens": "160"}
    async with httpx.AsyncClient(timeout=60.0) as client:
        r = await client.post(f"{GEMMA4_URL}/v1/audio-chat", files=files, data=data)
    r.raise_for_status()
    j = r.json()
    return (j.get("text") or "").strip()


async def _conversation_turn_with_response(
    ws: WebSocket,
    voice_id: str,
    language: str,
    user_text_for_history: str,
    response_text: str,
    history: list[dict],
    interrupt_flag: dict,
):
    """Variant of _conversation_turn used when the response was already
    produced upstream (e.g. by Gemma 4). Skips the LLM call, just runs TTS."""
    turn_start = time.time()
    history.append({"role": "user", "content": user_text_for_history})

    if not _looks_arabic(response_text):
        # Defensive — Gemma 4 is consistent in Arabic but if a future model
        # drifts we still ship a polite Arabic line instead of garbage audio.
        response_text = "عذراً، لم أفهم ما طلبته بشكل واضح. هل يمكنك إعادة سؤالك من فضلك؟"

    history.append({"role": "assistant", "content": response_text})
    await ws.send_json({"type": "response_text", "text": response_text, "language": language})
    await ws.send_json({"type": "audio_meta", "sample_rate": SAMPLE_RATE, "format": "pcm_s16le"})

    first_emitted = False
    ttfa_ms = 0.0
    chunks = 0
    assert _tts_lock is not None
    async with _serialize(_tts_lock, _tts_stats):
        async for pcm in _generate_stream(response_text, voice_id, None):
            if interrupt_flag["value"]:
                break
            if not first_emitted:
                ttfa_ms = (time.time() - turn_start) * 1000
                first_emitted = True
            await ws.send_bytes(pcm)
            chunks += 1

    total_ms = (time.time() - turn_start) * 1000
    await ws.send_json({
        "type": "turn_done",
        "ttfa_ms": round(ttfa_ms),
        "total_ms": round(total_ms),
        "chunks": chunks,
        "engine": "gemma4",
    })


async def _conversation_turn(
    ws: WebSocket,
    voice_id: str,
    language: str,
    user_text: str,
    history: list[dict],
    interrupt_flag: dict,
):
    """Run one turn of: append user → LLM → TTS-stream → append assistant."""
    turn_start = time.time()
    history.append({"role": "user", "content": user_text})

    loop = asyncio.get_event_loop()
    assert _llm_lock is not None
    async with _serialize(_llm_lock, _llm_stats):
        response_text = await loop.run_in_executor(
            None, lambda: _llm_generate_sync(history, max_new_tokens=256)
        )
    response_text = response_text.strip()

    # Language guard: if Qwen drifted into Chinese/English (it sometimes
    # does on ambiguous Arabic input), retry once with an even more
    # explicit "Arabic only, even if input is unclear" instruction.
    if not _looks_arabic(response_text):
        retry_msgs = list(history) + [
            {
                "role": "assistant",
                "content": response_text,
            },
            {
                "role": "user",
                "content": (
                    "أعد ردّك السابق بالعربية الفصحى فقط. ممنوع استخدام أي "
                    "لغة غير العربية مهما كانت الظروف. اجعل الرد جملة "
                    "واحدة قصيرة."
                ),
            },
        ]
        async with _serialize(_llm_lock, _llm_stats):
            retry = await loop.run_in_executor(
                None, lambda: _llm_generate_sync(retry_msgs, max_new_tokens=200)
            )
        retry = retry.strip()
        if _looks_arabic(retry):
            response_text = retry
        else:
            # Hard fallback — better to apologize than to ship Chinese audio.
            response_text = "عذراً، لم أفهم ما طلبته بشكل واضح. هل يمكنك إعادة سؤالك من فضلك؟"

    history.append({"role": "assistant", "content": response_text})
    await ws.send_json({"type": "response_text", "text": response_text, "language": language})

    if not response_text:
        await ws.send_json({"type": "turn_done", "total_ms": round((time.time() - turn_start) * 1000)})
        return

    await ws.send_json({"type": "audio_meta", "sample_rate": SAMPLE_RATE, "format": "pcm_s16le"})

    first_emitted = False
    ttfa_ms = 0.0
    chunks = 0
    assert _tts_lock is not None
    async with _serialize(_tts_lock, _tts_stats):
        async for pcm in _generate_stream(response_text, voice_id, None):
            if interrupt_flag["value"]:
                break
            if not first_emitted:
                ttfa_ms = (time.time() - turn_start) * 1000
                first_emitted = True
            await ws.send_bytes(pcm)
            chunks += 1

    total_ms = (time.time() - turn_start) * 1000
    await ws.send_json({
        "type": "turn_done",
        "ttfa_ms": round(ttfa_ms),
        "total_ms": round(total_ms),
        "chunks": chunks,
    })
    return response_text


@app.websocket("/v1/text-to-speech/{voice_id}/ws")
async def tts_ws(ws: WebSocket, voice_id: str):
    """WebSocket TTS — emits {meta} → binary PCM chunks → {ttfa} → {done}.

    Auth: pass api key as `?api_key=...` query string (since headers limited in WS).
    Send: {"text": "...", "voice_settings": {...}}  (model_id optional)
    """
    if API_KEY:
        token = ws.query_params.get("api_key", "")
        if token != API_KEY:
            await ws.close(code=1008); return
    await ws.accept()
    request_start = time.time()
    try:
        data = await ws.receive_json()
        text = data.get("text", "").strip()
        if not text:
            await ws.send_json({"type": "error", "message": "text required"}); return
        settings_dict = data.get("voice_settings") or {}
        settings = VoiceSettings(**settings_dict) if settings_dict else None
        auto_diacritize = bool(data.get("auto_diacritize", False))

        if auto_diacritize:
            loop = asyncio.get_event_loop()
            assert _llm_lock is not None
            async with _serialize(_llm_lock, _llm_stats):
                text = await loop.run_in_executor(None, _diacritize_arabic, text)

        await ws.send_json({"type": "meta", "sample_rate": SAMPLE_RATE, "format": "pcm_s16le", "voice_id": voice_id})

        first_emitted = False
        chunk_idx = 0
        assert _tts_lock is not None
        async with _serialize(_tts_lock, _tts_stats):
            async for pcm in _generate_stream(text, voice_id, settings):
                if not first_emitted:
                    ttfa_ms = (time.time() - request_start) * 1000
                    await ws.send_json({"type": "ttfa", "ms": round(ttfa_ms, 0)})
                    first_emitted = True
                await ws.send_bytes(pcm)
                chunk_idx += 1

        await ws.send_json({
            "type": "done",
            "total_chunks": chunk_idx,
            "total_wall_ms": round((time.time() - request_start) * 1000, 0),
        })
        # Send a clean close-frame so the client's onclose fires with code 1000.
        try:
            await ws.close(code=1000)
        except Exception:
            pass
    except WebSocketDisconnect:
        pass
    except Exception as e:
        import traceback; traceback.print_exc()
        try: await ws.send_json({"type": "error", "message": str(e)[:500]})
        except Exception: pass
        try: await ws.close(code=1011)
        except Exception: pass


# ============================================================
# Root → docs redirect
# ============================================================
@app.get("/", include_in_schema=False)
async def root():
    return JSONResponse({
        "name": "Mostashar Voice API",
        "version": "1.0.0",
        "docs": "/docs",
        "openapi": "/openapi.json",
        "health": "/v1/health",
    })


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("MV_PORT", "8080")), log_level="info")
