"""
Mostashar Voice — Production REST API (ElevenLabs-style)

Clean, stable HTTP/WebSocket API consumable from any client (NestJS, OpenAI SDK
patterns, curl, browser fetch, etc.).

API conventions (mirror ElevenLabs where reasonable):
  - All endpoints under /v1/
  - Auth: header `xi-api-key: <key>` OR `Authorization: Bearer <key>` (set MV_API_KEY env to enable)
  - Voice CRUD:
      GET    /v1/voices                       → list
      GET    /v1/voices/{voice_id}            → detail
      GET    /v1/voices/{voice_id}/preview    → reference audio (WAV)
      POST   /v1/voices/add                   → multipart clone
      DELETE /v1/voices/{voice_id}
  - TTS:
      POST   /v1/text-to-speech/{voice_id}           → full WAV
      POST   /v1/text-to-speech/{voice_id}/stream    → chunked PCM (HTTP)
      WS     /v1/text-to-speech/{voice_id}/ws        → WebSocket (more control)
  - Models:
      GET    /v1/models
  - Health:
      GET    /v1/health
  - Docs:
      GET    /docs       (Swagger UI auto-generated by FastAPI)
      GET    /openapi.json

Errors:
  Standard JSON shape: {"error": {"code": "...", "message": "...", "status": int}}

Audio output formats supported on output_format query/body param:
  - pcm_24000  → raw PCM int16 LE 24kHz mono (chunked)
  - wav        → WAV with header (full or chunked-with-fixed-header)

Run:
  env MV_MODEL=aoi-ot/VibeVoice-Large MV_DIFF_STEPS=15 MV_API_KEY=secret123 python server_v5_api.py
"""
from __future__ import annotations

import os
import io
import time
import json
import asyncio
import threading
import struct
import uuid
import re
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Optional, AsyncGenerator

import numpy as np
import soundfile as sf
import librosa
import torch
from fastapi import (
    FastAPI, WebSocket, WebSocketDisconnect, UploadFile, File, Form,
    HTTPException, Header, Depends, Query, Path as PathParam,
)
from fastapi.responses import StreamingResponse, FileResponse, Response, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# --- config ---
MODEL_NAME = os.environ.get("MV_MODEL", "aoi-ot/VibeVoice-Large")
DIFFUSION_STEPS = int(os.environ.get("MV_DIFF_STEPS", "15"))
CFG_SCALE = float(os.environ.get("MV_CFG", "1.8"))
SAMPLE_RATE = 24000
DEFAULT_REF = os.environ.get("MV_REF", "/workspace/refs/01.mp3")
VOICES_DIR = os.environ.get("MV_VOICES_DIR", "/workspace/refs/voices")
API_KEY = os.environ.get("MV_API_KEY", "")  # if empty, auth is disabled
os.makedirs(VOICES_DIR, exist_ok=True)

# --- shared state ---
processor = None
model = None
voice_profiles: dict[str, dict] = {}


# ============================================================
# Models (Pydantic)
# ============================================================
class VoiceSettings(BaseModel):
    cfg_scale: float = Field(default=1.8, ge=1.0, le=3.0)
    diffusion_steps: int = Field(default=15, ge=5, le=60)
    seed: int = Field(default=42)


class TTSRequest(BaseModel):
    text: str = Field(..., min_length=1, max_length=5000)
    model_id: str = Field(default="vibevoice-large")
    output_format: str = Field(default="pcm_24000", pattern="^(pcm_24000|wav)$")
    voice_settings: Optional[VoiceSettings] = None


class VoiceMeta(BaseModel):
    voice_id: str
    name: str
    language: str
    dur_s: float
    preview_url: str
    created_at: Optional[int]


class VoicesListResponse(BaseModel):
    voices: list[VoiceMeta]


class CloneResponse(BaseModel):
    voice_id: str
    name: str
    language: str
    dur_s: float


class ModelInfo(BaseModel):
    model_id: str
    name: str
    languages: list[str]
    can_clone: bool
    description: str


class HealthResponse(BaseModel):
    status: str
    model: str
    diffusion_steps: int
    voices_count: int
    gpu_mem_gb: float
    version: str


# ============================================================
# Auth
# ============================================================
def require_api_key(
    xi_api_key: Optional[str] = Header(None, alias="xi-api-key"),
    authorization: Optional[str] = Header(None),
):
    """Validate API key. If MV_API_KEY env is unset, auth is bypassed."""
    if not API_KEY:
        return
    candidate = xi_api_key
    if not candidate and authorization and authorization.lower().startswith("bearer "):
        candidate = authorization[7:]
    if candidate != API_KEY:
        raise HTTPException(status_code=401, detail="invalid_api_key")


# ============================================================
# Voice persistence
# ============================================================
def _meta_path(voice_id: str) -> str: return os.path.join(VOICES_DIR, f"{voice_id}.json")
def _wav_path(voice_id: str) -> str: return os.path.join(VOICES_DIR, f"{voice_id}.wav")


def _slugify(s: str) -> str:
    # keep ASCII alnum + Arabic block + hyphen/underscore
    s = re.sub(r"[^\w؀-ۿ\-]+", "-", (s or "").strip(), flags=re.UNICODE)
    s = re.sub(r"-+", "-", s).strip("-")
    return s[:40] or "voice"


def _load_voice_from_disk(voice_id: str) -> Optional[dict]:
    wp = _wav_path(voice_id)
    if not os.path.exists(wp):
        return None
    audio_np, _ = librosa.load(wp, sr=SAMPLE_RATE)
    meta = {"voice_id": voice_id, "name": voice_id, "language": "ar"}
    mp = _meta_path(voice_id)
    if os.path.exists(mp):
        try: meta.update(json.load(open(mp, encoding="utf-8")))
        except Exception: pass
    profile = {
        "voice_id": voice_id,
        "ref_audio_np": audio_np,
        "ref_audio_dur_s": len(audio_np) / SAMPLE_RATE,
        "name": meta.get("name", voice_id),
        "language": meta.get("language", "ar"),
        "created_at": meta.get("created_at"),
    }
    voice_profiles[voice_id] = profile
    return profile


def _get_voice(voice_id: str) -> dict:
    if voice_id in voice_profiles:
        return voice_profiles[voice_id]
    p = _load_voice_from_disk(voice_id)
    if p is not None:
        return p
    raise HTTPException(status_code=404, detail={"error": {"code": "voice_not_found", "message": f"voice {voice_id} not found", "status": 404}})


def _save_voice(voice_id: str, audio_np: np.ndarray, name: str, language: str) -> dict:
    if len(audio_np) > 30 * SAMPLE_RATE:
        audio_np = audio_np[: 30 * SAMPLE_RATE]
    sf.write(_wav_path(voice_id), audio_np, SAMPLE_RATE)
    meta = {
        "voice_id": voice_id,
        "name": name,
        "language": language,
        "created_at": int(time.time()),
        "dur_s": len(audio_np) / SAMPLE_RATE,
    }
    with open(_meta_path(voice_id), "w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)
    profile = {
        "voice_id": voice_id,
        "ref_audio_np": audio_np,
        "ref_audio_dur_s": meta["dur_s"],
        "name": name,
        "language": language,
        "created_at": meta["created_at"],
    }
    voice_profiles[voice_id] = profile
    return profile


# ============================================================
# Audio helpers
# ============================================================
def _wav_header(num_samples: int, sr: int = SAMPLE_RATE, channels: int = 1, bits: int = 16) -> bytes:
    """Standard WAV header for raw PCM16."""
    byte_rate = sr * channels * bits // 8
    block_align = channels * bits // 8
    data_size = num_samples * block_align
    return (
        b"RIFF" + struct.pack("<I", 36 + data_size) + b"WAVE"
        + b"fmt " + struct.pack("<IHHIIHH", 16, 1, channels, sr, byte_rate, block_align, bits)
        + b"data" + struct.pack("<I", data_size)
    )


def _wav_streaming_header(sr: int = SAMPLE_RATE) -> bytes:
    """WAV header with unknown length (data_size = 0xFFFFFFFF) for streaming."""
    return _wav_header(0xFFFFFFFF // 2, sr)


def _chunk_to_pcm_bytes(audio_tensor: torch.Tensor) -> bytes:
    a = audio_tensor.detach().cpu().float().numpy().flatten()
    a = (np.clip(a, -1.0, 1.0) * 32767).astype(np.int16)
    return a.tobytes()


# ============================================================
# Generation (shared between non-streaming + streaming)
# ============================================================
def _generate_full(text: str, voice_id: str, settings: Optional[VoiceSettings] = None) -> np.ndarray:
    """Synchronous full generation, returns float32 audio."""
    profile = _get_voice(voice_id)
    if settings:
        model.set_ddpm_inference_steps(num_steps=settings.diffusion_steps)
    speaker_text = "Speaker 1: " + text
    inputs = processor(
        text=[speaker_text],
        voice_samples=[[profile["ref_audio_np"]]],
        return_tensors="pt", padding=True,
    )
    inputs = {k: (v.to("cuda") if hasattr(v, "to") else v) for k, v in inputs.items()}
    torch.manual_seed(settings.seed if settings else 42)
    with torch.no_grad():
        out = model.generate(
            **inputs, max_new_tokens=None,
            cfg_scale=settings.cfg_scale if settings else CFG_SCALE,
            tokenizer=processor.tokenizer,
            generation_config={"do_sample": False, "num_beams": 1},
            verbose=False, show_progress_bar=False,
        )
    return out.speech_outputs[0].cpu().float().numpy().flatten()


async def _generate_stream(text: str, voice_id: str, settings: Optional[VoiceSettings] = None) -> AsyncGenerator[bytes, None]:
    """Async generator yielding PCM16LE chunks as the model produces them."""
    from vibevoice.modular.streamer import AudioStreamer

    profile = _get_voice(voice_id)
    if settings:
        model.set_ddpm_inference_steps(num_steps=settings.diffusion_steps)
    speaker_text = "Speaker 1: " + text
    inputs = processor(
        text=[speaker_text],
        voice_samples=[[profile["ref_audio_np"]]],
        return_tensors="pt", padding=True,
    )
    inputs = {k: (v.to("cuda") if hasattr(v, "to") else v) for k, v in inputs.items()}

    streamer = AudioStreamer(batch_size=1, stop_signal=None, timeout=30.0)
    cfg = settings.cfg_scale if settings else CFG_SCALE
    seed = settings.seed if settings else 42

    def run_generate():
        try:
            torch.manual_seed(seed)
            with torch.no_grad():
                model.generate(
                    **inputs, max_new_tokens=None, cfg_scale=cfg,
                    tokenizer=processor.tokenizer,
                    generation_config={"do_sample": False, "num_beams": 1},
                    verbose=False, show_progress_bar=False,
                    audio_streamer=streamer,
                )
        except Exception:
            import traceback; traceback.print_exc()
            streamer.end()

    threading.Thread(target=run_generate, daemon=True).start()
    loop = asyncio.get_event_loop()
    while True:
        try:
            chunk = await loop.run_in_executor(None, lambda: streamer.audio_queues[0].get(timeout=30.0))
        except Exception:
            break
        if chunk is None or chunk is streamer.stop_signal:
            break
        yield _chunk_to_pcm_bytes(chunk)


# ============================================================
# Lifespan
# ============================================================
@asynccontextmanager
async def lifespan(app: FastAPI):
    global processor, model
    print(f"[startup] loading {MODEL_NAME} with flash_attention_2...")
    t0 = time.time()
    from vibevoice.modular.modeling_vibevoice_inference import VibeVoiceForConditionalGenerationInference
    from vibevoice.processor.vibevoice_processor import VibeVoiceProcessor
    processor = VibeVoiceProcessor.from_pretrained(MODEL_NAME)
    model = VibeVoiceForConditionalGenerationInference.from_pretrained(
        MODEL_NAME, torch_dtype=torch.bfloat16, device_map="cuda",
        attn_implementation="flash_attention_2",
    )
    model.eval()
    model.set_ddpm_inference_steps(num_steps=DIFFUSION_STEPS)
    print(f"[startup] loaded in {time.time()-t0:.1f}s, GPU mem={torch.cuda.memory_allocated()/1e9:.1f}GB")

    # auto-discover voices on disk
    for f in os.listdir(VOICES_DIR):
        if f.endswith(".wav"):
            try: _load_voice_from_disk(f[:-4])
            except Exception as e: print(f"  failed to load {f}: {e}")

    if "default" not in voice_profiles and os.path.exists(DEFAULT_REF):
        audio_np, _ = librosa.load(DEFAULT_REF, sr=SAMPLE_RATE)
        _save_voice("default", audio_np, "Default", "ar")

    print(f"[startup] voices loaded: {len(voice_profiles)} ({list(voice_profiles.keys())[:5]}...)")
    print(f"[startup] auth: {'enabled' if API_KEY else 'DISABLED (set MV_API_KEY env to enable)'}")

    # warmup
    try:
        _ = _generate_full("مرحبا", "default" if "default" in voice_profiles else next(iter(voice_profiles)))
        print("[startup] warmup done")
    except Exception as e:
        print(f"[startup] warmup error: {e}")
    yield


# ============================================================
# App
# ============================================================
app = FastAPI(
    title="Mostashar Voice API",
    description="Real-time Arabic voice cloning + TTS. ElevenLabs-style REST API. "
                "Auth via `xi-api-key` header (or `Authorization: Bearer ...`). "
                "Set MV_API_KEY env to enable; left empty disables auth (development).",
    version="1.0.0",
    lifespan=lifespan,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], allow_methods=["*"], allow_headers=["*"],
)


# ============================================================
# Health
# ============================================================
@app.get("/v1/health", response_model=HealthResponse, tags=["misc"])
async def health():
    return HealthResponse(
        status="ok",
        model=MODEL_NAME,
        diffusion_steps=DIFFUSION_STEPS,
        voices_count=len(voice_profiles),
        gpu_mem_gb=round(torch.cuda.memory_allocated() / 1e9, 2),
        version="1.0.0",
    )


@app.get("/health", include_in_schema=False)
async def health_legacy(): return await health()


# ============================================================
# Models
# ============================================================
@app.get("/v1/models", response_model=list[ModelInfo], tags=["models"])
async def list_models(_=Depends(require_api_key)):
    return [
        ModelInfo(
            model_id="vibevoice-large",
            name="VibeVoice Large (8B)",
            languages=["ar", "en", "multilingual"],
            can_clone=True,
            description="Premium quality voice cloning. ~334ms TTFA streaming.",
        ),
    ]


# ============================================================
# Voices
# ============================================================
@app.get("/v1/voices", response_model=VoicesListResponse, tags=["voices"])
async def list_voices(_=Depends(require_api_key)):
    voices = []
    for vid, p in voice_profiles.items():
        voices.append(VoiceMeta(
            voice_id=vid,
            name=p.get("name", vid),
            language=p.get("language", "ar"),
            dur_s=round(p.get("ref_audio_dur_s", 0), 2),
            preview_url=f"/v1/voices/{vid}/preview",
            created_at=p.get("created_at"),
        ))
    voices.sort(key=lambda v: -(v.created_at or 0))
    return VoicesListResponse(voices=voices)


@app.get("/v1/voices/{voice_id}", response_model=VoiceMeta, tags=["voices"])
async def get_voice(voice_id: str = PathParam(...), _=Depends(require_api_key)):
    p = _get_voice(voice_id)
    return VoiceMeta(
        voice_id=p["voice_id"], name=p["name"], language=p["language"],
        dur_s=round(p["ref_audio_dur_s"], 2),
        preview_url=f"/v1/voices/{voice_id}/preview",
        created_at=p.get("created_at"),
    )


@app.get("/v1/voices/{voice_id}/preview", tags=["voices"])
async def voice_preview(voice_id: str, _=Depends(require_api_key)):
    _get_voice(voice_id)  # ensures it's loaded / 404 if missing
    return FileResponse(_wav_path(voice_id), media_type="audio/wav")


@app.post("/v1/voices/add", response_model=CloneResponse, tags=["voices"])
async def add_voice(
    name: str = Form(..., min_length=1, max_length=80),
    language: str = Form("ar", pattern="^(ar|en|multi)$"),
    start_s: float = Form(0.0, ge=0),
    end_s: float = Form(30.0, gt=0, le=300),
    files: list[UploadFile] = File(..., description="One audio file (mp3/wav/m4a/webm)"),
    _=Depends(require_api_key),
):
    if not files:
        raise HTTPException(400, "no audio file provided")
    audio = files[0]
    audio_bytes = await audio.read()
    try:
        buf = io.BytesIO(audio_bytes)
        audio_np, _sr = librosa.load(buf, sr=SAMPLE_RATE)
    except Exception as e:
        raise HTTPException(400, f"failed to decode audio: {e}")

    s0 = max(0, int(start_s * SAMPLE_RATE))
    s1 = min(len(audio_np), int(end_s * SAMPLE_RATE))
    if s1 - s0 < 3 * SAMPLE_RATE:
        raise HTTPException(400, "selection must be at least 3 seconds")
    audio_np = audio_np[s0:s1]
    if len(audio_np) > 30 * SAMPLE_RATE:
        audio_np = audio_np[: 30 * SAMPLE_RATE]

    voice_id = f"{_slugify(name)}-{uuid.uuid4().hex[:6]}"
    profile = _save_voice(voice_id, audio_np, name, language)
    return CloneResponse(
        voice_id=voice_id, name=name, language=language,
        dur_s=round(profile["ref_audio_dur_s"], 2),
    )


@app.delete("/v1/voices/{voice_id}", tags=["voices"])
async def delete_voice(voice_id: str, _=Depends(require_api_key)):
    if voice_id == "default":
        raise HTTPException(403, "cannot delete default voice")
    if voice_id in voice_profiles:
        del voice_profiles[voice_id]
    for path in (_wav_path(voice_id), _meta_path(voice_id)):
        if os.path.exists(path):
            os.remove(path)
    return {"ok": True, "voice_id": voice_id}


# ============================================================
# Text-to-Speech
# ============================================================
@app.post("/v1/text-to-speech/{voice_id}", tags=["tts"], responses={
    200: {"content": {"audio/wav": {}}, "description": "Full WAV audio"},
})
async def tts_full(
    voice_id: str,
    req: TTSRequest,
    _=Depends(require_api_key),
):
    """Generate the full audio (non-streaming). Returns WAV file."""
    audio = _generate_full(req.text, voice_id, req.voice_settings)
    a16 = (np.clip(audio, -1.0, 1.0) * 32767).astype(np.int16)
    body = _wav_header(len(a16)) + a16.tobytes()
    return Response(content=body, media_type="audio/wav")


@app.post("/v1/text-to-speech/{voice_id}/stream", tags=["tts"])
async def tts_stream(
    voice_id: str,
    req: TTSRequest,
    _=Depends(require_api_key),
):
    """Streaming TTS via HTTP chunked transfer encoding.

    output_format=pcm_24000 → raw PCM16LE 24kHz mono chunks (Content-Type: audio/pcm)
    output_format=wav       → WAV header + chunked PCM (Content-Type: audio/wav)
    """
    request_start = time.time()
    is_wav = req.output_format == "wav"
    media_type = "audio/wav" if is_wav else "audio/pcm"

    async def generator():
        if is_wav:
            yield _wav_streaming_header(SAMPLE_RATE)
        first_emitted = False
        async for chunk in _generate_stream(req.text, voice_id, req.voice_settings):
            if not first_emitted:
                ttfa_ms = (time.time() - request_start) * 1000
                print(f"[tts_stream] voice={voice_id} TTFA={ttfa_ms:.0f}ms")
                first_emitted = True
            yield chunk

    headers = {
        "X-Sample-Rate": str(SAMPLE_RATE),
        "X-Audio-Format": "pcm_s16le",
        "Cache-Control": "no-cache",
    }
    return StreamingResponse(generator(), media_type=media_type, headers=headers)


@app.websocket("/v1/text-to-speech/{voice_id}/ws")
async def tts_ws(ws: WebSocket, voice_id: str):
    """WebSocket TTS — emits {meta} → binary PCM chunks → {ttfa} → {done}.

    Auth: pass api key as `?api_key=...` query string (since headers limited in WS).
    Send: {"text": "...", "voice_settings": {...}}  (model_id optional)
    """
    if API_KEY:
        token = ws.query_params.get("api_key", "")
        if token != API_KEY:
            await ws.close(code=1008); return
    await ws.accept()
    request_start = time.time()
    try:
        data = await ws.receive_json()
        text = data.get("text", "").strip()
        if not text:
            await ws.send_json({"type": "error", "message": "text required"}); return
        settings_dict = data.get("voice_settings") or {}
        settings = VoiceSettings(**settings_dict) if settings_dict else None

        await ws.send_json({"type": "meta", "sample_rate": SAMPLE_RATE, "format": "pcm_s16le", "voice_id": voice_id})

        first_emitted = False
        chunk_idx = 0
        async for pcm in _generate_stream(text, voice_id, settings):
            if not first_emitted:
                ttfa_ms = (time.time() - request_start) * 1000
                await ws.send_json({"type": "ttfa", "ms": round(ttfa_ms, 0)})
                first_emitted = True
            await ws.send_bytes(pcm)
            chunk_idx += 1

        await ws.send_json({
            "type": "done",
            "total_chunks": chunk_idx,
            "total_wall_ms": round((time.time() - request_start) * 1000, 0),
        })
    except WebSocketDisconnect:
        pass
    except Exception as e:
        import traceback; traceback.print_exc()
        try: await ws.send_json({"type": "error", "message": str(e)[:500]})
        except Exception: pass


# ============================================================
# Root → docs redirect
# ============================================================
@app.get("/", include_in_schema=False)
async def root():
    return JSONResponse({
        "name": "Mostashar Voice API",
        "version": "1.0.0",
        "docs": "/docs",
        "openapi": "/openapi.json",
        "health": "/v1/health",
    })


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("MV_PORT", "8080")), log_level="info")
